### PR TITLE
Integrated view in ownCloud

### PR DESCRIPTION
**Pull request by LEDfan**
WIP

### CODE REVIEW

**Comment by LEDfan** [comment]
cc @jancborchardt @jbtbnl @fossxplorer This is how it looks now:
schermafbeelding 2015-01-30 op 11 29 48

I'm now going to integrate the chat messages itself.

**Comment by LEDfan** [comment]
And a first raw implementation of the chat boxes:
schermafbeelding 2015-01-30 op 11 50 25

**Comment by jancborchardt** [comment]
@LEDfan I would say instead of having these small individual windows overlaying the interface, the bottom half of the sidebar should show the currently active conversation. Only one at a time, and the buddy list above will allow you to switch between them.

**Comment by jancborchardt** [comment]
Btw, great progress! :)

**Comment by LEDfan** [comment]
Great idea @jancborchardt !

**Comment by jbtbnl** [comment]
Good progress @LEDfan! I agree with the suggestion of @jancborchardt - overlaying windows are soo web 1.0 :smile:

**Comment by LEDfan** [comment]
>overlaying windows are soo web 1.0 :smile: 
Time to kill it with fire :smiley:

**Comment by LEDfan** [comment]
Postponed to v0.5.0

**Comment by LEDfan** [comment]
@jancborchardt a first implementation of the chat-window inside the sidebar:
schermafbeelding 2015-02-13 op 09 06 33
And when the sidebar is hidden:
schermafbeelding 2015-02-13 op 09 07 30

**Comment by LEDfan** [comment]
@jancborchardt @jbtbnl I merged the first iteration, please comment in #134

**Pull request merged**
